version: '3'
services:
  redis:
    image: "redislabs/redisearch:latest"
    container_name: redis
    ports:
      - "6379:6379"

  insight:
    image: "redislabs/redisinsight:latest"
    container_name: insight
    ports:
      - "8001:8001"
    volumes:
      - ../redisinsight:/db
    depends_on:
      - redis

